### ISSUE TITLE
vectrex add-on isn't starting reliably.

### ISSUE THREAD

**Issue by beta-tester** [kodi-game/game.libretro.vecx#6]
### Describe the bug
Here is a clear and concise description of what the problem is:
on LibreELEC 9.0.0 / Kodi 18.0 on RPi3B, i can start vectrex games, but only under specific conditions *).
on LibreELEC 9.0.1 / Kodi 18.1 on RPi3B, i can't start vextrex games at all.
kodi crash as soon as i try to start a game...
black screen and after a while kodi userinterface comes back - has crashed.

*) the special conditions  on LibreELEC 9.0.0 / Kodi 18.0 are (as far i could reproduce):
the vectrec add-on has to be installed, re-installed or updated recently without rebooting the RPi3.
as soon after the RPi3 was rebooted, the ability to play vectrex games is broken again.
then i have to renew the add-on in one or the other way again.

### To Reproduce

[vectrex is broken with LibreELEC 9.0.1 (was working with 9.0.0)](https://forum.libreelec.tv/core/ticketsystem/ticket/61-vectrex-is-broken-with-libreelec-9-0-1-was-working-with-9-0-0/)

### Debuglog

The debuglog can be found here:
[log](https://paste.kodi.tv/mojodoxuxo.kodi)
[crash.log](https://paste.kodi.tv/ivokulehov.kodi)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

Operating system version/name:

Kodi version:
LibreELEC 9.0.0 / Kodi 18.0
LibreELEC 9.0.1 / Kodi 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by eigendude** [comment]
Thanks for reporting. Sent a fix upstream: https://github.com/libretro/libretro-vecx/pull/26

**Comment by garbear** [comment]
Thanks for reporting. Sent a fix upstream: https://github.com/libretro/libretro-vecx/pull/26

**Comment by beta-tester** [comment]
> 
> 
> Thanks for reporting. Sent a fix upstream: [libretro/libretro-vecx#26](https://github.com/libretro/libretro-vecx/pull/26)

is it already available as an updated version in the Add-On repository?
because i don't get a new version number (is still 1.2.0.3.114) of the **GCE-Vectrex (vecx)** add-on to see in LibreELEC 9.0.1.

**Comment by garbear** [comment]
No, it will take an indeterminate amount of time for any releases to include this commit.

**Comment by garbear** [comment]
LibreELEC 9.0.2 will contain this fix.

**Comment by garbear** [comment]
In the meantime, you can try this add-on from @MilhouseVM: http://milhouse.libreelec.tv/other/game.libretro.vecx-1.2.0.4.113.zip

**Comment by beta-tester** [comment]
thank you very much, with the zip file vectrex works again.

**Comment by beta-tester** [comment]
i just upgraded my LibreELEC 9.0.1 to the official version 9.0.2 MR.
then i upgraded the zip version of the addon to the add-on of that LibreELEC 9.0.2 but there is still version 1.2.0.3.114 shown and that isn't working.

i reinstalled the ZIP version 1.2.0.4.113 to have a working add-on.

**Comment by beta-tester** [comment]
seems to be reliable starting.
tested with official version 1.2.0.4.1 on official (beta)
http://releases.libreelec.tv/LibreELEC-RPi2.arm-9.1.501.img.gz
